# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_1/zynq_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1 || ORIG_REF_NAME==zynq_1} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_processing_system7_0_0/zynq_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_axi_gpio_0_0/zynq_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_axi_gpio_1_0/zynq_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_xbar_0/zynq_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_xbar_0 || ORIG_REF_NAME==zynq_1_xbar_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_ps7_0_axi_periph_0/zynq_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_rst_ps7_0_50M_0/zynq_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_axi_timer_0_0/zynq_1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_axi_timer_0_0 || ORIG_REF_NAME==zynq_1_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_accu_0_0/zynq_1_accu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_accu_0_0 || ORIG_REF_NAME==zynq_1_accu_0_0} -quiet] -quiet

# IP: bd/zynq_1/ip/zynq_1_auto_pc_0/zynq_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_auto_pc_0 || ORIG_REF_NAME==zynq_1_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq_1/zynq_1_ooc.xdc
